services:
  database:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:8
    volumes:
      - ./src/${DB_PROJECT_DIR}/MySQL:/var/lib/mysql
      - ./docker/mysql.conf:/etc/mysql/my.cnf
    ports:
      - ${DB_CONTAINER_EXTERNAL_PORT}:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: senhafoda
      MYSQL_DATABASE: projeto-cenut-database
    networks:
      - denut

  app:
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${CONTAINER_EXTERNAL_PORT}:80
    volumes:
      - ./src/${PROJECT_DIR}:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - denut

networks:
  denut:
    driver: bridge